# Generated by Django 5.0 on 2024-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_service_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
