# Generated by Django 5.0 on 2024-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
