# Generated by Django 5.0 on 2024-01-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_expertise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
